../bin/InferStudy -e ../data/abalone/abalone -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/adult/adult -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/australian/australian -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/automobile/automobile -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/balance/balance -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/banana/banana -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/bands/bands -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/bupa/bupa -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/census/census -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/cleveland/cleveland -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/coil2000/coil2000 -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/connect-4/connect-4 -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/covtype_2_vs_1/covtype_2_vs_1 -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/crx/crx -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/fars_0_vs_4_/fars_0_vs_4_ -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/flare/flare -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/german/german -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/heart/heart -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/ionosphere/ionosphere -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/iris/iris -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/led7digit/led7digit -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/letter/letter -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/magic/magic -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/mammographic/mammographic -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/movement_libras/movement_libras -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/newthyroid/newthyroid -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/page-blocks/page-blocks -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/penbased/penbased -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/phoneme/phoneme -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/pima/pima -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/ring/ring -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/saheart/saheart -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/satimage/satimage -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/segment/segment -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/shuttle/shuttle -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/sonar/sonar -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/spambase/spambase -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/spectfheart/spectfheart -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/texture/texture -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/thyroid/thyroid -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/twonorm/twonorm -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/vehicle/vehicle -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/vowel/vowel -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/wine/wine -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/winequality-red/winequality-red -model 3 -nlabel 5 -maxrules 1024
../bin/InferStudy -e ../data/winequality-white/winequality-white -model 3 -nlabel 5 -maxrules 1024
#../bin/InferStudy -e ../data/kddcup_full_normalsus_DOS/kddcup_full_normalsus_DOS -model 3 -nlabel 5 -maxrules 1024
#../bin/InferStudy -e ../data/susy/susy -model 3 -nlabel 5 -maxrules 1024
#../bin/InferStudy -e ../data/higgs/higgs -model 3 -nlabel 5 -maxrules 1024 -PerCentOnTest 0.001
#../bin/InferStudy -e ../data/hepmassAll/hepmassAll -model 3 -nlabel 5 -maxrules 1024 -PerCentOnTest 0.001
