#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/abalone/abalone 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/adult/adult 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/app/app 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/appendicitis/appendicitis 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/australian/australian 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/automobile/automobile 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/balance/balance 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/banana/banana 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/bands/bands 1 5
.#/WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/breast/breast 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/bupa/bupa 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/car/car 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/census/census 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/chess/chess 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/cleveland/cleveland 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/coil2000/coil2000 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/connect-4/connect-4 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/contraceptive/contraceptive 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/crx/crx 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/dermatology/dermatology 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/ecoli/ecoli 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/fars/fars 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/flare/flare 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/german/german 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/glass/glass 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/haberman/haberman 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/hayes-roth/hayes-roth 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/heart/heart 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/hepatitis/hepatitis 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/housevotes/housevotes 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/ionosphere/ionosphere 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/iris/iris 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/kddcup/kddcup 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/kr-vs-k/kr-vs-k 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/led7digit/led7digit 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/letter/letter 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/lymphography/lymphography 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/magic/magic 1 5
# ./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/mammographic/mammographic 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/marketing/marketing 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/monk-2/monk-2 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/movement_libras/movement_libras 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/mushroom/mushroom 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/newthyroid/newthyroid 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/nursery/nursery 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/optdigits/optdigits 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/page-blocks/page-blocks 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/penbased/penbased 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/phoneme/phoneme 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/phonome/phonome 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/pima/pima 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/poker/poker 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/post-operative/post-operative 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/ring/ring 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/saheart/saheart 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/satimage/satimage 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/segment/segment 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/shuttle/shuttle 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/sonar/sonar 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/spambase/spambase 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/spectfheart/spectfheart 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/splice/splice 1 5
.#/WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/tae/tae 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/texture/texture 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/thyroid/thyroid 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/tic-tac-toe/tic-tac-toe 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/titanic/titanic 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/twonorm/twonorm 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/vehicle/vehicle 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/vowel/vowel 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/wdbc/wdbc 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/wine/wine 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/winequality-red/winequality-red 1 5
./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/winequality-white/winequality-white 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/wisconsin/wisconsin 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/yeast/yeast 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/aprendizajegenetico/SlvDataBasesToKeel/zoo/zoo 1 5
