./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/abalone/abalone 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/adult/adult 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/app/app 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/appendicitis/appendicitis 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/australian/australian 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/automobile/automobile 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/balance/balance 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/banana/banana 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/bands/bands 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/breast/breast 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/bupa/bupa 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/car/car 1 2
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/census/census 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/chess/chess 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/cleveland/cleveland 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/coil2000/coil2000 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/connect-4/connect-4 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/contraceptive/contraceptive 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/crx/crx 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/dermatology/dermatology 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ecoli/ecoli 1 2
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/fars/fars 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/flare/flare 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/german/german 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/glass/glass 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/haberman/haberman 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/hayes-roth/hayes-roth 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/heart/heart 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/hepatitis/hepatitis 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/housevotes/housevotes 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ionosphere/ionosphere 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/iris/iris 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/kddcup/kddcup 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/kr-vs-k/kr-vs-k 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/led7digit/led7digit 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/letter/letter 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/lymphography/lymphography 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/magic/magic 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/mammographic/mammographic 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/marketing/marketing 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/monk-2/monk-2 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/movement_libras/movement_libras 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/mushroom/mushroom 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/newthyroid/newthyroid 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/nursery/nursery 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/optdigits/optdigits 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/page-blocks/page-blocks 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/penbased/penbased 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/phoneme/phoneme 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/phonome/phonome 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/pima/pima 1 2
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/poker/poker 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/post-operative/post-operative 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ring/ring 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/saheart/saheart 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/satimage/satimage 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/segment/segment 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/shuttle/shuttle 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/sonar/sonar 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/spambase/spambase 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/spectfheart/spectfheart 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/splice/splice 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/tae/tae 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/texture/texture 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/thyroid/thyroid 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/tic-tac-toe/tic-tac-toe 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/titanic/titanic 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/twonorm/twonorm 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/vehicle/vehicle 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/vowel/vowel 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wdbc/wdbc 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wine/wine 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/winequality-red/winequality-red 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/winequality-white/winequality-white 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wisconsin/wisconsin 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/yeast/yeast 1 2
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/zoo/zoo 1 2


./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/abalone/abalone 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/adult/adult 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/app/app 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/appendicitis/appendicitis 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/australian/australian 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/automobile/automobile 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/balance/balance 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/banana/banana 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/bands/bands 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/breast/breast 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/bupa/bupa 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/car/car 1 3
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/census/census 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/chess/chess 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/cleveland/cleveland 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/coil2000/coil2000 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/connect-4/connect-4 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/contraceptive/contraceptive 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/crx/crx 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/dermatology/dermatology 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ecoli/ecoli 1 3
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/fars/fars 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/flare/flare 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/german/german 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/glass/glass 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/haberman/haberman 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/hayes-roth/hayes-roth 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/heart/heart 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/hepatitis/hepatitis 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/housevotes/housevotes 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ionosphere/ionosphere 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/iris/iris 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/kddcup/kddcup 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/kr-vs-k/kr-vs-k 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/led7digit/led7digit 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/letter/letter 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/lymphography/lymphography 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/magic/magic 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/mammographic/mammographic 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/marketing/marketing 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/monk-2/monk-2 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/movement_libras/movement_libras 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/mushroom/mushroom 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/newthyroid/newthyroid 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/nursery/nursery 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/optdigits/optdigits 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/page-blocks/page-blocks 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/penbased/penbased 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/phoneme/phoneme 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/phonome/phonome 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/pima/pima 1 3
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/poker/poker 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/post-operative/post-operative 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ring/ring 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/saheart/saheart 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/satimage/satimage 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/segment/segment 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/shuttle/shuttle 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/sonar/sonar 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/spambase/spambase 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/spectfheart/spectfheart 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/splice/splice 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/tae/tae 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/texture/texture 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/thyroid/thyroid 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/tic-tac-toe/tic-tac-toe 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/titanic/titanic 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/twonorm/twonorm 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/vehicle/vehicle 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/vowel/vowel 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wdbc/wdbc 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wine/wine 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/winequality-red/winequality-red 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/winequality-white/winequality-white 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wisconsin/wisconsin 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/yeast/yeast 1 3
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/zoo/zoo 1 3


./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/abalone/abalone 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/adult/adult 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/app/app 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/appendicitis/appendicitis 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/australian/australian 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/automobile/automobile 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/balance/balance 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/banana/banana 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/bands/bands 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/breast/breast 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/bupa/bupa 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/car/car 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/census/census 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/chess/chess 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/cleveland/cleveland 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/coil2000/coil2000 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/connect-4/connect-4 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/contraceptive/contraceptive 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/crx/crx 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/dermatology/dermatology 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ecoli/ecoli 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/fars/fars 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/flare/flare 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/german/german 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/glass/glass 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/haberman/haberman 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/hayes-roth/hayes-roth 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/heart/heart 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/hepatitis/hepatitis 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/housevotes/housevotes 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ionosphere/ionosphere 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/iris/iris 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/kddcup/kddcup 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/kr-vs-k/kr-vs-k 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/led7digit/led7digit 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/letter/letter 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/lymphography/lymphography 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/magic/magic 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/mammographic/mammographic 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/marketing/marketing 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/monk-2/monk-2 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/movement_libras/movement_libras 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/mushroom/mushroom 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/newthyroid/newthyroid 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/nursery/nursery 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/optdigits/optdigits 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/page-blocks/page-blocks 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/penbased/penbased 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/phoneme/phoneme 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/phonome/phonome 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/pima/pima 1 5
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/poker/poker 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/post-operative/post-operative 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ring/ring 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/saheart/saheart 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/satimage/satimage 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/segment/segment 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/shuttle/shuttle 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/sonar/sonar 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/spambase/spambase 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/spectfheart/spectfheart 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/splice/splice 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/tae/tae 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/texture/texture 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/thyroid/thyroid 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/tic-tac-toe/tic-tac-toe 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/titanic/titanic 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/twonorm/twonorm 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/vehicle/vehicle 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/vowel/vowel 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wdbc/wdbc 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wine/wine 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/winequality-red/winequality-red 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/winequality-white/winequality-white 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wisconsin/wisconsin 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/yeast/yeast 1 5
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/zoo/zoo 1 5

./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/abalone/abalone 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/adult/adult 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/app/app 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/appendicitis/appendicitis 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/australian/australian 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/automobile/automobile 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/balance/balance 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/banana/banana 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/bands/bands 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/breast/breast 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/bupa/bupa 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/car/car 1 7
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/census/census 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/chess/chess 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/cleveland/cleveland 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/coil2000/coil2000 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/connect-4/connect-4 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/contraceptive/contraceptive 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/crx/crx 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/dermatology/dermatology 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ecoli/ecoli 1 7
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/fars/fars 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/flare/flare 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/german/german 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/glass/glass 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/haberman/haberman 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/hayes-roth/hayes-roth 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/heart/heart 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/hepatitis/hepatitis 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/housevotes/housevotes 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ionosphere/ionosphere 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/iris/iris 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/kddcup/kddcup 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/kr-vs-k/kr-vs-k 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/led7digit/led7digit 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/letter/letter 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/lymphography/lymphography 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/magic/magic 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/mammographic/mammographic 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/marketing/marketing 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/monk-2/monk-2 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/movement_libras/movement_libras 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/mushroom/mushroom 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/newthyroid/newthyroid 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/nursery/nursery 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/optdigits/optdigits 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/page-blocks/page-blocks 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/penbased/penbased 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/phoneme/phoneme 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/phonome/phonome 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/pima/pima 1 7
#./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/poker/poker 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/post-operative/post-operative 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/ring/ring 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/saheart/saheart 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/satimage/satimage 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/segment/segment 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/shuttle/shuttle 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/sonar/sonar 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/spambase/spambase 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/spectfheart/spectfheart 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/splice/splice 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/tae/tae 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/texture/texture 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/thyroid/thyroid 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/tic-tac-toe/tic-tac-toe 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/titanic/titanic 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/twonorm/twonorm 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/vehicle/vehicle 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/vowel/vowel 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wdbc/wdbc 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wine/wine 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/winequality-red/winequality-red 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/winequality-white/winequality-white 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/wisconsin/wisconsin 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/yeast/yeast 1 7
./WyM_Ver /home/fgr/SoftwarePropio/HeredadoDeCalafate/aprendizajegenetico/SlvDataBasesToKeel/zoo/zoo 1 7
